//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18046.
// 
#pragma warning disable 1591

namespace Invert911.InvertCommon.Invert911service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Invert911ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Invert911Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcessMobileMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessMobileMessageTestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Invert911Service() {
            this.Url = global::Invert911.InvertCommon.Properties.Settings.Default.Invert911_InvertCommon_Invert911service_Invert911Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessMobileMessageCompletedEventHandler ProcessMobileMessageCompleted;
        
        /// <remarks/>
        public event ProcessMobileMessageTestCompletedEventHandler ProcessMobileMessageTestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessMobileMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessMobileMessage(string Message) {
            object[] results = this.Invoke("ProcessMobileMessage", new object[] {
                        Message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessMobileMessageAsync(string Message) {
            this.ProcessMobileMessageAsync(Message, null);
        }
        
        /// <remarks/>
        public void ProcessMobileMessageAsync(string Message, object userState) {
            if ((this.ProcessMobileMessageOperationCompleted == null)) {
                this.ProcessMobileMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessMobileMessageOperationCompleted);
            }
            this.InvokeAsync("ProcessMobileMessage", new object[] {
                        Message}, this.ProcessMobileMessageOperationCompleted, userState);
        }
        
        private void OnProcessMobileMessageOperationCompleted(object arg) {
            if ((this.ProcessMobileMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessMobileMessageCompleted(this, new ProcessMobileMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessMobileMessageTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessMobileMessageTest(string Message) {
            object[] results = this.Invoke("ProcessMobileMessageTest", new object[] {
                        Message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessMobileMessageTestAsync(string Message) {
            this.ProcessMobileMessageTestAsync(Message, null);
        }
        
        /// <remarks/>
        public void ProcessMobileMessageTestAsync(string Message, object userState) {
            if ((this.ProcessMobileMessageTestOperationCompleted == null)) {
                this.ProcessMobileMessageTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessMobileMessageTestOperationCompleted);
            }
            this.InvokeAsync("ProcessMobileMessageTest", new object[] {
                        Message}, this.ProcessMobileMessageTestOperationCompleted, userState);
        }
        
        private void OnProcessMobileMessageTestOperationCompleted(object arg) {
            if ((this.ProcessMobileMessageTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessMobileMessageTestCompleted(this, new ProcessMobileMessageTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessMobileMessageCompletedEventHandler(object sender, ProcessMobileMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessMobileMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessMobileMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessMobileMessageTestCompletedEventHandler(object sender, ProcessMobileMessageTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessMobileMessageTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessMobileMessageTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591