//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Agency
    {
        public i9Agency()
        {
            this.i9AVL = new HashSet<i9AVL>();
            this.i9AVLEvent = new HashSet<i9AVLEvent>();
            this.i9AVLHistory = new HashSet<i9AVLHistory>();
            this.i9CADServiceCall = new HashSet<i9CADServiceCall>();
            this.i9Citation = new HashSet<i9Citation>();
            this.i9Code = new HashSet<i9Code>();
            this.i9CodeSet = new HashSet<i9CodeSet>();
            this.i9ConfigurationSetting = new HashSet<i9ConfigurationSetting>();
            this.i9DynamicEntryConfig = new HashSet<i9DynamicEntryConfig>();
            this.i9Event = new HashSet<i9Event>();
            this.i9FieldContact = new HashSet<i9FieldContact>();
            this.i9Gang = new HashSet<i9Gang>();
            this.i9LawIncident = new HashSet<i9LawIncident>();
            this.i9Location = new HashSet<i9Location>();
            this.i9MessageInbox = new HashSet<i9MessageInbox>();
            this.i9Pawn = new HashSet<i9Pawn>();
            this.i9Person = new HashSet<i9Person>();
            this.i9Property = new HashSet<i9Property>();
            this.i9SecurityGroup = new HashSet<i9SecurityGroup>();
            this.i9SecurityGroupModule = new HashSet<i9SecurityGroupModule>();
            this.i9SecurityGroupTask = new HashSet<i9SecurityGroupTask>();
            this.i9SysLog = new HashSet<i9SysLog>();
            this.i9SysPersonnel = new HashSet<i9SysPersonnel>();
            this.i9Vehicle = new HashSet<i9Vehicle>();
            this.i9Warrant = new HashSet<i9Warrant>();
        }
    
        public string AgencyName { get; set; }
        public string AgencyDesc { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public System.Guid i9AgencyID { get; set; }
    
        public virtual ICollection<i9AVL> i9AVL { get; set; }
        public virtual ICollection<i9AVLEvent> i9AVLEvent { get; set; }
        public virtual ICollection<i9AVLHistory> i9AVLHistory { get; set; }
        public virtual ICollection<i9CADServiceCall> i9CADServiceCall { get; set; }
        public virtual ICollection<i9Citation> i9Citation { get; set; }
        public virtual ICollection<i9Code> i9Code { get; set; }
        public virtual ICollection<i9CodeSet> i9CodeSet { get; set; }
        public virtual ICollection<i9ConfigurationSetting> i9ConfigurationSetting { get; set; }
        public virtual ICollection<i9DynamicEntryConfig> i9DynamicEntryConfig { get; set; }
        public virtual ICollection<i9Event> i9Event { get; set; }
        public virtual ICollection<i9FieldContact> i9FieldContact { get; set; }
        public virtual ICollection<i9Gang> i9Gang { get; set; }
        public virtual ICollection<i9LawIncident> i9LawIncident { get; set; }
        public virtual ICollection<i9Location> i9Location { get; set; }
        public virtual ICollection<i9MessageInbox> i9MessageInbox { get; set; }
        public virtual ICollection<i9Pawn> i9Pawn { get; set; }
        public virtual ICollection<i9Person> i9Person { get; set; }
        public virtual ICollection<i9Property> i9Property { get; set; }
        public virtual ICollection<i9SecurityGroup> i9SecurityGroup { get; set; }
        public virtual ICollection<i9SecurityGroupModule> i9SecurityGroupModule { get; set; }
        public virtual ICollection<i9SecurityGroupTask> i9SecurityGroupTask { get; set; }
        public virtual ICollection<i9SysLog> i9SysLog { get; set; }
        public virtual ICollection<i9SysPersonnel> i9SysPersonnel { get; set; }
        public virtual ICollection<i9Vehicle> i9Vehicle { get; set; }
        public virtual ICollection<i9Warrant> i9Warrant { get; set; }
    }
}
