//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Arrest
    {
        public string ActivityCategory { get; set; }
        public string TransactionNumber { get; set; }
        public string ORI_OriginatingAgencyIdentifier { get; set; }
        public string ArrestDate { get; set; }
        public string NarrativeAccountDescription { get; set; }
        public string NarrativeAccountDescriptionDate { get; set; }
        public string ArrestTypeCode { get; set; }
        public string Arrestee { get; set; }
        public string ArrestingOfficer { get; set; }
        public System.Guid i9ArrestID { get; set; }
        public System.Guid i9EventID { get; set; }
    
        public virtual i9Event i9Event { get; set; }
    }
}
