//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Attachment
    {
        public i9Attachment()
        {
            this.i9AttachmentData = new HashSet<i9AttachmentData>();
        }
    
        public string AttachmentName { get; set; }
        public string AttachmentNotes { get; set; }
        public Nullable<System.DateTime> Capturedate { get; set; }
        public string ImageTypeCode { get; set; }
        public string ImageTypeText { get; set; }
        public System.Guid i9AttachmentID { get; set; }
        public System.Guid i9EventID { get; set; }
        public byte[] AttachmentFile { get; set; }
    
        public virtual i9Event i9Event { get; set; }
        public virtual ICollection<i9AttachmentData> i9AttachmentData { get; set; }
    }
}
