//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9AVL
    {
        public string VehicleID { get; set; }
        public Nullable<System.DateTime> PositionDateTime { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<decimal> Velocity { get; set; }
        public Nullable<decimal> Heading { get; set; }
        public Nullable<decimal> Disconnect { get; set; }
        public Nullable<double> MapX { get; set; }
        public Nullable<double> MapY { get; set; }
        public System.Guid i9AVLID { get; set; }
        public System.Guid i9AgencyID { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
    }
}
