//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9CADServiceCall
    {
        public string ActivityCategory { get; set; }
        public string ServiceCallORI { get; set; }
        public string ServiceCallDate { get; set; }
        public string ServiceCallTime { get; set; }
        public string PriorityCode { get; set; }
        public string SourceCode { get; set; }
        public string SourceText { get; set; }
        public string ServiceCaller { get; set; }
        public string Operator { get; set; }
        public string CADDispatcher { get; set; }
        public string TelephoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string ServiceCallOtherContactAddress { get; set; }
        public string DispatchLocation { get; set; }
        public string DispatchLocationOwnerName { get; set; }
        public System.Guid i9CADServiceCallID { get; set; }
        public System.Guid i9AgencyID { get; set; }
        public System.Guid i9EventID { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
        public virtual i9Event i9Event { get; set; }
    }
}
