//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9DynamicEntryConfig
    {
        public string ModuleSection { get; set; }
        public Nullable<int> Enabled { get; set; }
        public string LabelText { get; set; }
        public string CtrlWidth { get; set; }
        public string CtrlHeight { get; set; }
        public string CtrlFont { get; set; }
        public string CtrlForGroundColor { get; set; }
        public string CtrlBackGroundColor { get; set; }
        public Nullable<int> PrintEnabled { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string ToolPopup { get; set; }
        public string DataType { get; set; }
        public string CtrlTypeName { get; set; }
        public System.Guid i9DynamicEntryConfigID { get; set; }
        public System.Guid i9AgencyID { get; set; }
        public Nullable<float> DisplayOrder { get; set; }
        public int IsReadOnly { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
    }
}
