//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9DynamicEntry
    {
        public string ModuleSection { get; set; }
        public string ModuleSectionDesc { get; set; }
        public string DynamicEntryTable { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
