//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9DynamicEntryRule
    {
        public long i9DynanicEntryConfigID { get; set; }
        public Nullable<long> i9DynanicEntryConfigID2 { get; set; }
        public string RuleType { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public System.Guid i9DynamicEntryRuleID { get; set; }
    }
}
