//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9EmailModule
    {
        public string ToEmailAddress { get; set; }
        public string CCEmailAddress { get; set; }
        public string BCCEmailAddress { get; set; }
        public string FromEmailAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public byte EmailStatusFlag { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertENTUserAccountId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdateENTUserAccountId { get; set; }
        public byte[] Version { get; set; }
        public System.Guid i9EmailModuleID { get; set; }
    }
}
