//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9LawIncident
    {
        public i9LawIncident()
        {
            this.i9ModusOperandi = new HashSet<i9ModusOperandi>();
            this.i9Offense = new HashSet<i9Offense>();
        }
    
        public string ActivityCategory { get; set; }
        public string IncidentNumber { get; set; }
        public string ORI { get; set; }
        public string IncidentReportDate { get; set; }
        public string BeginDate { get; set; }
        public string BeginTime { get; set; }
        public string EndDate { get; set; }
        public string EndTime { get; set; }
        public string NarrativeAccountDescription { get; set; }
        public string StatusCode { get; set; }
        public string StatusText { get; set; }
        public string StatusDate { get; set; }
        public string EvidenceHeldIndicator { get; set; }
        public string FactorCode { get; set; }
        public string FactorText { get; set; }
        public string ExceptionalClearanceCode { get; set; }
        public string ExceptionalClearanceDate { get; set; }
        public string WeatherCode { get; set; }
        public string WeatherText { get; set; }
        public string IncidentLightingCode { get; set; }
        public string IncidentLightingText { get; set; }
        public string AgencyNotificationIndicator { get; set; }
        public string IncidentDisseminationLevelCode { get; set; }
        public string InvolvedProperty { get; set; }
        public string Evidence { get; set; }
        public string IncidentSubject { get; set; }
        public string IncidentVictim { get; set; }
        public string IncidentWitness { get; set; }
        public string IncidentOtherInvolvedPerson { get; set; }
        public string IncidentOffense { get; set; }
        public string IncidentServiceCall { get; set; }
        public string ReportingOfficer { get; set; }
        public int SupplementNumber { get; set; }
        public string Summary { get; set; }
        public System.Guid i9LawIncidentID { get; set; }
        public System.Guid i9AgencyID { get; set; }
        public System.Guid i9EventID { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
        public virtual i9Event i9Event { get; set; }
        public virtual i9LawIncident i9LawIncident1 { get; set; }
        public virtual i9LawIncident i9LawIncident2 { get; set; }
        public virtual ICollection<i9ModusOperandi> i9ModusOperandi { get; set; }
        public virtual ICollection<i9Offense> i9Offense { get; set; }
    }
}
