//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Location
    {
        public long LocationMVI { get; set; }
        public string LocationTypeCode { get; set; }
        public string LocationTypeText { get; set; }
        public string FullStreetAddress { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string StreetPredirection { get; set; }
        public string StreetPostdirection { get; set; }
        public string Apartment { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string StateText { get; set; }
        public string LotNumber { get; set; }
        public string ZipCode { get; set; }
        public string ZipCodeExtension { get; set; }
        public string County { get; set; }
        public string CountryCode { get; set; }
        public string CountryText { get; set; }
        public string Highway { get; set; }
        public string MileMarker { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public System.Guid i9LocationID { get; set; }
        public System.Guid i9AgencyID { get; set; }
        public System.Guid i9EventID { get; set; }
        public string i9ModuleSectionID { get; set; }
        public string LocationRemarks { get; set; }
        public string Beat { get; set; }
        public Nullable<System.Guid> i9PersonID { get; set; }
        public Nullable<System.Guid> i9VehicleID { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
        public virtual i9Event i9Event { get; set; }
        public virtual i9ModuleSection i9ModuleSection { get; set; }
        public virtual i9Person i9Person { get; set; }
        public virtual i9Vehicle i9Vehicle { get; set; }
    }
}
