//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9ModuleSection
    {
        public i9ModuleSection()
        {
            this.i9Location = new HashSet<i9Location>();
            this.i9Person = new HashSet<i9Person>();
        }
    
        public string i9ModuleSectionID { get; set; }
        public string ModuleSectionDesc { get; set; }
    
        public virtual ICollection<i9Location> i9Location { get; set; }
        public virtual ICollection<i9Person> i9Person { get; set; }
    }
}
