//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Module
    {
        public string ClassName { get; set; }
        public string ModuleName { get; set; }
        public string Section { get; set; }
        public bool PopupPage { get; set; }
        public bool DesktopEnabled { get; set; }
        public bool MobileEnabled { get; set; }
        public string ModuleType { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public System.Guid i9ModuleID { get; set; }
        public string ModuleKey { get; set; }
    }
}
