//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9ModuleReportNumber
    {
        public string i9ModuleID { get; set; }
        public long ReportNumber { get; set; }
        public string NumberPrefix { get; set; }
        public string NumberSubFix { get; set; }
        public Nullable<int> Length { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string ResetReportNumber { get; set; }
        public int StartNumber { get; set; }
        public int EndNumber { get; set; }
        public int NumberLength { get; set; }
        public System.Guid i9ModuleReportNumberID { get; set; }
    }
}
