//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Narrative
    {
        public System.Guid i9NarrativeID { get; set; }
        public System.Guid i9EventID { get; set; }
        public string SummaryNarrative { get; set; }
        public string Narrative { get; set; }
        public string SummaryNarrativeFormat { get; set; }
        public string NarrativeFormat { get; set; }
    
        public virtual i9Event i9Event { get; set; }
    }
}
