//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Organization
    {
        public string OrganizationTypeCode { get; set; }
        public string OrganizationTypeText { get; set; }
        public string Description { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationIDValue { get; set; }
        public string IDEffectiveDate { get; set; }
        public string IDExpirationDate { get; set; }
        public string IDIssuingAuthority { get; set; }
        public string IDStatus { get; set; }
        public string IDType { get; set; }
        public string OrganizationTaxID { get; set; }
        public string FederalFirearmLicenseID { get; set; }
        public System.Guid i9OrganizationID { get; set; }
        public System.Guid i9EventID { get; set; }
    
        public virtual i9Event i9Event { get; set; }
    }
}
