//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PersonSubject
    {
        public string SubjectPerson { get; set; }
        public string Organization { get; set; }
        public string SequenceNumber { get; set; }
        public string ModusOperandiSubjectActionCode { get; set; }
        public string ModusOperandiSubjectActionText { get; set; }
        public string ModusOperandiObservationCode { get; set; }
        public string ModusOperandiObservationText { get; set; }
        public System.Guid i9PersonSubjectID { get; set; }
        public System.Guid i9PersonID { get; set; }
    
        public virtual i9Person i9Person { get; set; }
    }
}
