//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PersonMissing
    {
        public string MissingPerson { get; set; }
        public string MissingPersonCircumstanceCode { get; set; }
        public string MissingPersonCircumstanceText { get; set; }
        public string MissingPersonDeclarationDate { get; set; }
        public string MissingPersonDeclarationTime { get; set; }
        public string MissingPersonFoundDate { get; set; }
        public string MissingPersonFoundTime { get; set; }
        public string MissingPersonFoundIndicator { get; set; }
        public string MissingPersonLastSeenDate { get; set; }
        public string MissingPersonLastSeenTime { get; set; }
        public System.Guid i9PersonMissingID { get; set; }
        public System.Guid i9PersonID { get; set; }
    
        public virtual i9Person i9Person { get; set; }
    }
}
