//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PersonVictim
    {
        public string VictimOrganization { get; set; }
        public string VictimPerson { get; set; }
        public string VictimSequenceNumber { get; set; }
        public string ModusOperandiVictimActionCode { get; set; }
        public string ModusOperandiVictimActionText { get; set; }
        public string VictimTypeCode { get; set; }
        public string VictimTypeText { get; set; }
        public string AggravatedAssaultHomicideCircumstanceCode { get; set; }
        public string AggravatedAssaultHomicideCircumstanceText { get; set; }
        public string AdditionalJustifiableHomicideCode { get; set; }
        public string InjuryTypeCode { get; set; }
        public string InjuryTypeText { get; set; }
        public System.Guid i9PersonVictimID { get; set; }
        public System.Guid i9PersonID { get; set; }
    
        public virtual i9Person i9Person { get; set; }
    }
}
