//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PersonSMT
    {
        public string SMTCode { get; set; }
        public string SMTDescription { get; set; }
        public string SMTLocation { get; set; }
        public string Feature { get; set; }
        public System.Guid i9PersonSMTID { get; set; }
        public System.Guid i9PersonID { get; set; }
        public System.Guid i9EventID { get; set; }
    
        public virtual i9Event i9Event { get; set; }
        public virtual i9Person i9Person { get; set; }
    }
}
