//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PersonRelated
    {
        public Nullable<System.DateTime> RecordedDate { get; set; }
        public string InvolvementCode { get; set; }
        public System.Guid i9PersonRelatedID { get; set; }
        public System.Guid i9PersonID { get; set; }
        public System.Guid i9PersonIDRelated { get; set; }
    
        public virtual i9Person i9Person { get; set; }
        public virtual i9Person i9Person1 { get; set; }
    }
}
