//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Person
    {
        public i9Person()
        {
            this.i9Location = new HashSet<i9Location>();
            this.i9Person1 = new HashSet<i9Person>();
            this.i9PersonArrestee = new HashSet<i9PersonArrestee>();
            this.i9PersonMissing = new HashSet<i9PersonMissing>();
            this.i9PersonPhoto = new HashSet<i9PersonPhoto>();
            this.i9PersonRelated = new HashSet<i9PersonRelated>();
            this.i9PersonRelated1 = new HashSet<i9PersonRelated>();
            this.i9PersonSMT = new HashSet<i9PersonSMT>();
            this.i9PersonSubject = new HashSet<i9PersonSubject>();
            this.i9PersonVehicle = new HashSet<i9PersonVehicle>();
            this.i9PersonVictim = new HashSet<i9PersonVictim>();
        }
    
        public long PersonMNI { get; set; }
        public string PersonPotentialMatchID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string FullName { get; set; }
        public string PersonNameTypeCode { get; set; }
        public string SexCode { get; set; }
        public string RaceCode { get; set; }
        public string EthnicityCode { get; set; }
        public string BirthDate { get; set; }
        public string SSN { get; set; }
        public string FBINumber { get; set; }
        public string DriverLicenseNumber { get; set; }
        public string DriverLicenseExpirationDate { get; set; }
        public string DriverLicenseIssuingAuthorityCode { get; set; }
        public string DriverLicenseIssuingAuthorityText { get; set; }
        public string StateID { get; set; }
        public string StateIDIssuingAuthorityCode { get; set; }
        public string StateIDIssuingAuthorityText { get; set; }
        public string PassportID { get; set; }
        public string PassportIssuingCountryCode { get; set; }
        public string PassportExpirationDate { get; set; }
        public string AlienNumber { get; set; }
        public string USMarshalServiceFugitiveID { get; set; }
        public string RegisteredOffenderIndicator { get; set; }
        public string RegisteredOffenderNumber { get; set; }
        public string RegisteredOffenderIssuingAuthorityCode { get; set; }
        public string RegisteredOffenderIssuingAuthorityText { get; set; }
        public string PersonIdentificationNumberPID { get; set; }
        public string PIDTypeCode { get; set; }
        public string PIDIssuingAuthorityCode { get; set; }
        public string PIDIssuingAuthorityText { get; set; }
        public string PIDEffectiveDate { get; set; }
        public string PIDExpirationDate { get; set; }
        public string DNACollectionIndicator { get; set; }
        public string DNACollectionStatusText { get; set; }
        public string ResidentStatusCode { get; set; }
        public string OccupationCode { get; set; }
        public string OccupationText { get; set; }
        public string CitizenshipCode { get; set; }
        public string DigitalImage { get; set; }
        public string PersonPhysicalFeatureCode { get; set; }
        public string PhysicalFeatureDescription { get; set; }
        public string PhysicalFeatureImage { get; set; }
        public string PersonHeight { get; set; }
        public string MinimumHeight { get; set; }
        public string MaximumHeight { get; set; }
        public string HeightUnitCode { get; set; }
        public string Weight { get; set; }
        public string MinimumWeight { get; set; }
        public string MaximumWeight { get; set; }
        public string WeightUnitCode { get; set; }
        public string Age { get; set; }
        public string MinimumAge { get; set; }
        public string MaximumAge { get; set; }
        public string AgeUnitCode { get; set; }
        public string EyeColorCode { get; set; }
        public string HairColorCode { get; set; }
        public string HairLengthCode { get; set; }
        public string HairLengthText { get; set; }
        public string HairStyleCode { get; set; }
        public string HairStyleText { get; set; }
        public string HairDescription { get; set; }
        public string BuildCode { get; set; }
        public string BuildText { get; set; }
        public string EyewearCode { get; set; }
        public string EyewearText { get; set; }
        public string PersonHandednessCode { get; set; }
        public string DentalCharacteristicCode { get; set; }
        public string DentalCharacteristicText { get; set; }
        public string SpeechCode { get; set; }
        public string SpeechText { get; set; }
        public string FacialHairCode { get; set; }
        public string FacialHairText { get; set; }
        public string SkinToneCode { get; set; }
        public string CautionInformationCode { get; set; }
        public string CautionInformationText { get; set; }
        public string PersonCriminalInvolvementCode { get; set; }
        public string PersonMaritalStatus { get; set; }
        public int SequenceNumber { get; set; }
        public System.Guid i9PersonID { get; set; }
        public System.Guid i9EventID { get; set; }
        public System.Guid i9AgencyID { get; set; }
        public string i9ModuleSectionID { get; set; }
        public Nullable<System.Guid> i9PersonAKAID { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
        public virtual i9Event i9Event { get; set; }
        public virtual ICollection<i9Location> i9Location { get; set; }
        public virtual i9ModuleSection i9ModuleSection { get; set; }
        public virtual ICollection<i9Person> i9Person1 { get; set; }
        public virtual i9Person i9Person2 { get; set; }
        public virtual ICollection<i9PersonArrestee> i9PersonArrestee { get; set; }
        public virtual ICollection<i9PersonMissing> i9PersonMissing { get; set; }
        public virtual ICollection<i9PersonPhoto> i9PersonPhoto { get; set; }
        public virtual ICollection<i9PersonRelated> i9PersonRelated { get; set; }
        public virtual ICollection<i9PersonRelated> i9PersonRelated1 { get; set; }
        public virtual ICollection<i9PersonSMT> i9PersonSMT { get; set; }
        public virtual ICollection<i9PersonSubject> i9PersonSubject { get; set; }
        public virtual ICollection<i9PersonVehicle> i9PersonVehicle { get; set; }
        public virtual ICollection<i9PersonVictim> i9PersonVictim { get; set; }
    }
}
