//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PhoneNumber
    {
        public string CountryCode { get; set; }
        public string CityCode { get; set; }
        public string NumberAreaCode { get; set; }
        public string ExchangeID { get; set; }
        public string NumberSubscriberID { get; set; }
        public string Suffix { get; set; }
        public string NumberFull { get; set; }
        public string NumberType { get; set; }
        public System.Guid i9PhoneNumberID { get; set; }
    }
}
