//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PropertyExplosive
    {
        public string ComponentCode { get; set; }
        public string ComponentText { get; set; }
        public string ContainerCode { get; set; }
        public string ContainerText { get; set; }
        public string FillerCode { get; set; }
        public string FillerText { get; set; }
        public string ExplosiveIgnitionCode { get; set; }
        public string ExplosiveIgnitionText { get; set; }
        public System.Guid i9PropertyExplosiveID { get; set; }
        public System.Guid i9PropertyID { get; set; }
    
        public virtual i9Property i9Property { get; set; }
    }
}
