//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9PropertyHazardousMaterial
    {
        public string HazardousMaterialCode { get; set; }
        public string HazardousMaterialText { get; set; }
        public string HazardousMaterialQuantity { get; set; }
        public string HazardousMaterialMeasureCode { get; set; }
        public string HazardousMaterialContainerDescription { get; set; }
        public string HazardousMaterialSubstanceForm { get; set; }
        public System.Guid i9PropertyHazardousMaterialID { get; set; }
        public System.Guid i9PropertyID { get; set; }
    
        public virtual i9Property i9Property { get; set; }
    }
}
