//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Property
    {
        public i9Property()
        {
            this.i9PropertyEvidence = new HashSet<i9PropertyEvidence>();
            this.i9PropertyExplosive = new HashSet<i9PropertyExplosive>();
            this.i9PropertyFirearm = new HashSet<i9PropertyFirearm>();
            this.i9PropertyHazardousMaterial = new HashSet<i9PropertyHazardousMaterial>();
            this.i9PropertyImage = new HashSet<i9PropertyImage>();
            this.i9PropertySecurities = new HashSet<i9PropertySecurities>();
        }
    
        public long PropertyMPI { get; set; }
        public string PropertyStatusCode { get; set; }
        public string PropertyTypeCode { get; set; }
        public string PropertyTypeText { get; set; }
        public string PropertyValue { get; set; }
        public string PropertyValueTypeCode { get; set; }
        public string PropertyValueTypeText { get; set; }
        public string DispositionDate { get; set; }
        public string DigitalImage { get; set; }
        public string SerialNumber { get; set; }
        public string PropertyDescription { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string PropertyRFID { get; set; }
        public string KnifeTypeCode { get; set; }
        public string KnifeTypeText { get; set; }
        public string HouseholdGoodsTypeCode { get; set; }
        public string HouseholdGoodsTypeText { get; set; }
        public string LivestockPetTypeCode { get; set; }
        public string LivestockPetTypeText { get; set; }
        public string GrainTypeCode { get; set; }
        public string GrainTypeText { get; set; }
        public string CreditBankIDCardTypeCode { get; set; }
        public string CreditBankIDCardTypeText { get; set; }
        public string ConsumableGoodsTypeCode { get; set; }
        public string ConsumableGoodsTypeText { get; set; }
        public string ConstructionMaterialTypeCode { get; set; }
        public string ConstructionMaterialTypeText { get; set; }
        public string ElectronicEquipmentTypeCode { get; set; }
        public string ElectronicEquipmentTypeText { get; set; }
        public string ClothingTypeCode { get; set; }
        public string ClothingTypeText { get; set; }
        public string DeviceTypeCode { get; set; }
        public string DeviceTypeText { get; set; }
        public string DeviceStoredText { get; set; }
        public string DeviceAssignedTelephoneNumber { get; set; }
        public string DeviceEmailAddress { get; set; }
        public string DeviceOtherContactAddress { get; set; }
        public string DeviceElectronicSerialNumber_ESN { get; set; }
        public string DeviceInternationalMobileEquipmentIdentity_IMEI { get; set; }
        public string DrugTypeCode { get; set; }
        public string DrugTypeText { get; set; }
        public string DrugQuantity { get; set; }
        public string DrugMeasureCode { get; set; }
        public string DrugContainerDescription { get; set; }
        public string DrugSubstanceForm { get; set; }
        public string DrugFoundDescription { get; set; }
        public string JewelryTypeCode { get; set; }
        public string JewelryTypeText { get; set; }
        public System.Guid i9PropertyID { get; set; }
        public System.Guid i9AgencyID { get; set; }
        public System.Guid i9EventID { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
        public virtual i9Event i9Event { get; set; }
        public virtual ICollection<i9PropertyEvidence> i9PropertyEvidence { get; set; }
        public virtual ICollection<i9PropertyExplosive> i9PropertyExplosive { get; set; }
        public virtual ICollection<i9PropertyFirearm> i9PropertyFirearm { get; set; }
        public virtual ICollection<i9PropertyHazardousMaterial> i9PropertyHazardousMaterial { get; set; }
        public virtual ICollection<i9PropertyImage> i9PropertyImage { get; set; }
        public virtual ICollection<i9PropertySecurities> i9PropertySecurities { get; set; }
    }
}
