//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9RelatedRecord
    {
        public string RecordType { get; set; }
        public string RecordAgency { get; set; }
        public string RecordID { get; set; }
        public string Agency { get; set; }
        public string RelatedRecordType { get; set; }
        public string RelatedRecordAG { get; set; }
        public string RelatedRecordRecordID { get; set; }
        public string RelatedAGENCY { get; set; }
        public System.Guid i9RelatedRecordID { get; set; }
        public System.Guid i9EventID { get; set; }
    
        public virtual i9Event i9Event { get; set; }
    }
}
