//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9Vehicle
    {
        public i9Vehicle()
        {
            this.i9Location = new HashSet<i9Location>();
            this.i9PersonVehicle = new HashSet<i9PersonVehicle>();
            this.i9VehicleRecovery = new HashSet<i9VehicleRecovery>();
            this.i9VehicleTowed = new HashSet<i9VehicleTowed>();
        }
    
        public long VehicleMVI { get; set; }
        public string VIN { get; set; }
        public string ModelYear { get; set; }
        public string MakeCode { get; set; }
        public string ModelCode { get; set; }
        public string StyleCode { get; set; }
        public string ColorCode { get; set; }
        public string VehicleDescription { get; set; }
        public string LicenseNumber { get; set; }
        public string LicenseJurisdictionCode { get; set; }
        public string LicenseJurisdictionText { get; set; }
        public string LicenseYear { get; set; }
        public string LicenseTypeCode { get; set; }
        public string TailNumber { get; set; }
        public string FuselageColor { get; set; }
        public string WingColor { get; set; }
        public string EngineQuantity { get; set; }
        public string HomeAirportID { get; set; }
        public string HomeAirportName { get; set; }
        public string BoatTypeCode { get; set; }
        public string BoatTypeText { get; set; }
        public string SerialNumber { get; set; }
        public string BoatName { get; set; }
        public string OverallLength { get; set; }
        public string OverallLengthMeasureCode { get; set; }
        public string BoatPropulsionCode { get; set; }
        public string BoatPropulsionText { get; set; }
        public string BoatHomePort { get; set; }
        public string CoastGuardDocumentNumber { get; set; }
        public string BoatPartCategoryCode { get; set; }
        public string BoatPartCategoryText { get; set; }
        public string BoatEnginePowerDisplacement { get; set; }
        public string BoatEnginePowerDisplacementMeasureCode { get; set; }
        public string BoatHullShape { get; set; }
        public string BoatOuterHullMaterial { get; set; }
        public System.Guid i9VehicleID { get; set; }
        public System.Guid i9EventID { get; set; }
        public System.Guid i9AgencyID { get; set; }
    
        public virtual i9Agency i9Agency { get; set; }
        public virtual i9Event i9Event { get; set; }
        public virtual ICollection<i9Location> i9Location { get; set; }
        public virtual ICollection<i9PersonVehicle> i9PersonVehicle { get; set; }
        public virtual ICollection<i9VehicleRecovery> i9VehicleRecovery { get; set; }
        public virtual ICollection<i9VehicleTowed> i9VehicleTowed { get; set; }
    }
}
