//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invert911.InvertCommon.DataTypes.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class i9VehicleTowed
    {
        public System.Guid i9VehicleTowedID { get; set; }
        public System.Guid i9EventID { get; set; }
        public System.Guid i9VehicleID { get; set; }
        public string Notes { get; set; }
        public string TowedDate { get; set; }
        public string Condition { get; set; }
    
        public virtual i9Event i9Event { get; set; }
        public virtual i9Vehicle i9Vehicle { get; set; }
    }
}
